name: my second workflow
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: distro name and version
        run: cat /etc/os-release
      - name: kernel version, architecture and hostname
        run: uname -a
      - name: install inxi
        run: sudo apt-get update && sudo apt-get install -y inxi
      - name: full system summary including kernel version, ram, disk, cpu, gpu, network
        run: inxi -F
